import type { Product } from './commerce'

export const products: Product[] = [
  { id: 'royal-canin-fit', slug: 'royal-canin-regular-fit-32-cat-food', name: { en: 'Royal Canin Regular Fit 32 Adult Cat Food', bn: 'রয়্যাল ক্যানিন রেগুলার ফিট ৩২ অ্যাডাল্ট ক্যাট ফুড' }, description: { en: 'Complete and balanced dry food for adult cats aged 1-7 years with normal activity levels. Helps maintain ideal weight with adjusted calorie content.', bn: '১-৭ বছর বয়সী স্বাভাবিক কর্মক্ষম প্রাপ্তবয়স্ক বিড়ালের জন্য সম্পূর্ণ ও সুষম শুষ্ক খাবার। সামঞ্জস্যপূর্ণ ক্যালোরি সামগ্রীর মাধ্যমে আদর্শ ওজন বজায় রাখতে সাহায্য করে।' }, brand: 'Royal Canin', category: 'Cat', price: 2850, weightGrams: 2000, image: '/media/royal-canin-cat-food.jpg', inStock: true, badge: 'Best seller' },
  { id: 'smartheart-dog', slug: 'smartheart-adult-dog-food-roast-beef', name: { en: 'SmartHeart Adult Dog Food with Roast Beef', bn: 'স্মার্টহার্ট অ্যাডাল্ট ডগ ফুড — রোস্ট বিফ' }, description: { en: 'Premium nutrition with real roast beef for adult dogs. Supports healthy skin, coat, and digestion with balanced vitamins and minerals.', bn: 'প্রাপ্তবয়স্ক কুকুরের জন্য প্রকৃত রোস্ট বিফ সহ প্রিমিয়াম পুষ্টি। সুষম ভিটামিন ও খনিজের মাধ্যমে স্বাস্থ্যকর ত্বক, লোম ও হজমে সহায়তা করে।' }, brand: 'SmartHeart', category: 'Dog', price: 1480, weightGrams: 3000, compareAtPrice: 1580, image: '/media/smartheart-dog-food.jpg', inStock: true, badge: 'Sale' },
  { id: 'reflex-salmon', slug: 'reflex-plus-adult-cat-food-salmon', name: { en: 'Reflex Plus Adult Cat Food — Salmon', bn: 'রিফ্লেক্স প্লাস অ্যাডাল্ট ক্যাট ফুড — স্যামন' }, description: { en: 'Grain-free salmon recipe for adult cats. Rich in omega-3 and omega-6 fatty acids for healthy skin and a shiny coat.', bn: 'প্রাপ্তবয়স্ক বিড়ালের জন্য গ্রেইন-ফ্রি স্যামন রেসিপি। স্বাস্থ্যকর ত্বক ও উজ্জ্বল লোমের জন্য ওমেগা-৩ ও ওমেগা-৬ ফ্যাটি অ্যাসিড সমৃদ্ধ।' }, brand: 'Reflex Plus', category: 'Cat', price: 1250, weightGrams: 1500, image: '/media/reflex-salmon.jpg', inStock: true, badge: 'Vet recommended' },
  { id: 'wanpy-kitten', slug: 'wanpy-grain-free-kitten-food', name: { en: 'Wanpy Grain Free Kitten Food — Chicken', bn: 'ওয়ানপি গ্রেইন ফ্রি কিটেন ফুড — চিকেন' }, description: { en: 'Grain-free chicken formula specially designed for growing kittens. Supports healthy development with high-quality protein.', bn: 'বেড়ে ওঠা বাচ্চা বিড়ালের জন্য বিশেষভাবে তৈরি গ্রেইন-ফ্রি চিকেন ফর্মুলা। উচ্চমানের প্রোটিনের মাধ্যমে স্বাস্থ্যকর বিকাশে সহায়তা করে।' }, brand: 'Wanpy', category: 'Cat', price: 1200, weightGrams: 1000, image: '/media/wanpy-kitten.jpg', inStock: false },
  { id: 'jungle-rabbit', slug: 'jungle-premium-rabbit-food', name: { en: 'Jungle Premium Rabbit Food', bn: 'জাঙ্গল প্রিমিয়াম র‍্যাবিট ফুড' }, description: { en: 'Complete daily nutrition for adult rabbits. Made with natural ingredients and fortified with essential vitamins and fibre for healthy digestion.', bn: 'প্রাপ্তবয়স্ক খরগোশের জন্য সম্পূর্ণ দৈনিক পুষ্টি। প্রাকৃতিক উপাদানে তৈরি ও স্বাস্থ্যকর হজমের জন্য প্রয়োজনীয় ভিটামিন ও ফাইবার সমৃদ্ধ।' }, brand: 'Jungle', category: 'Rabbit', price: 420, weightGrams: 500, image: '/media/jungle-rabbit.jpg', inStock: true },
  { id: 'prama-dog', slug: 'prama-nori-seaweed-dog-treat', name: { en: 'Prama Nori Seaweed Adult Dog Treat', bn: 'প্রামা নরি সিউইড অ্যাডাল্ট ডগ ট্রিট' }, description: { en: 'Healthy and delicious seaweed-based treat for adult dogs. A natural source of iodine and minerals, perfect as a reward or snack.', bn: 'প্রাপ্তবয়স্ক কুকুরের জন্য স্বাস্থ্যকর ও সুস্বাদু সিউইড-ভিত্তিক ট্রিট। আয়োডিন ও খনিজের প্রাকৃতিক উৎস, পুরস্কার বা স্ন্যাক হিসেবে উপযুক্ত।' }, brand: 'Prama', category: 'Dog', price: 280, weightGrams: 100, image: '/media/prama-dog.jpg', inStock: true, badge: 'New' },
]

export const posts = [
  { slug: 'biral-bishakto-kichu-kheye-felle-ki-korbo', title: 'বিড়াল বিষাক্ত কিছু খেয়ে ফেললে কী করবো?', category: 'জরুরি যত্ন' },
  { slug: 'biral-hotat-durbol-hoye-gele-ki-korbo', title: 'বিড়াল হঠাৎ দুর্বল হয়ে গেলে কী করবো?', category: 'স্বাস্থ্য' },
  { slug: 'biraler-kan-theke-moyla-ba-durgondho-ashar-karon', title: 'বিড়ালের কান থেকে ময়লা বা দুর্গন্ধ আসার কারণ', category: 'স্বাস্থ্য' },
  { slug: 'biraler-mukhe-durgondho-keno-hoy', title: 'বিড়ালের মুখে দুর্গন্ধ কেন হয়?', category: 'ডেন্টাল কেয়ার' },
  { slug: 'biraler-shashkoshto-hole-ki-korbo', title: 'বিড়ালের শ্বাসকষ্ট হলে কী করবো?', category: 'জরুরি যত্ন' },
  { slug: 'kakhon-biralke-vet-dakterer-kache-niye-jaben', title: 'কখন বিড়ালকে ভেটেরিনারি ডাক্তারের কাছে নিয়ে যাবেন?', category: 'ভেট কেয়ার' },
]
